import decayTable from '../../../shared/decay.json';

/**
 * Canonical tracer-decay constants from shared/decay.json — the single source
 * of truth for the persistence fade. Consumers:
 *   - `durationToDecay()` / `effectiveDecay()` below (TS + the WASM dispatcher's
 *     fallback in `wasm/fallbacks/decay.ts`)
 *   - WGSL persistence (`shaders/persistence.ts`, via `DECAY_WGSL`)
 *   - GLSL persistence (`webgl/shaders/persistence.ts`, via `DECAY_GLSL`)
 *   - `cpp/decay_table.h` (generated by `npm run codegen:decay`), consumed by
 *     `chromashift_engine.cpp`'s `durationToDecay`
 *
 * `shaders/decayTable.test.ts` guards all four against divergence.
 */
export const DECAY = decayTable.constants;

/** Brightness fraction a tracer retains after its configured duration (10%). */
export const DECAY_RESIDUAL_BRIGHTNESS = DECAY.residualBrightness;

/** Decay exponent for a pixel where 2+ layers currently overlap — fades faster. */
export const DECAY_OVERLAP_EXPONENT = DECAY.overlapDecayExponent;

/** Decay exponent for a pixel with no current overlap — the plain decay rate. */
export const DECAY_IDLE_EXPONENT = DECAY.idleDecayExponent;

/**
 * Per-frame tracer decay multiplier — mirrors C++ durationToDecay and WGSL persistence.
 * After `durationMs` at `fps`, accumulated brightness reaches
 * `DECAY_RESIDUAL_BRIGHTNESS` (~10%).
 */
export function durationToDecay(durationMs: number, fps: number): number {
  if (durationMs <= 0) return 0.0;
  const frames = fps * durationMs / 1000;
  if (frames < 1) return 0.0;
  return Math.pow(DECAY_RESIDUAL_BRIGHTNESS, 1 / frames);
}

/**
 * The multiplier actually applied to the previous tracer value for one pixel —
 * the persistence passes raise `durationToDecay()`'s result to a per-pixel
 * exponent so overlapping pixels fade faster than idle ones.
 *
 * Reference implementation for the identical `pow(decayFactor, decayMod)` step
 * in `shaders/persistence.ts` (both the fused and the compute-fed composite
 * shader) and `webgl/shaders/persistence.ts`.
 */
export function effectiveDecay(decayFactor: number, hadOverlap: boolean): number {
  return Math.pow(
    decayFactor,
    hadOverlap ? DECAY_OVERLAP_EXPONENT : DECAY_IDLE_EXPONENT,
  );
}
