export const MAIN_VIEW_MODES = {
  PROCESSED_COMPOSITE: 0,
  FULL_RES_TRACER: 1,
  SOURCE_IMAGE: 2,
  LAYER_0: 3,
  LAYER_1: 4,
  LAYER_2: 5,
  COINCIDENCE_HEATMAP: 6,
  COMPARE_SOURCE_COMPOSITE: 7,
  REFERENCE_IMAGE: 8,
  PREVIOUS_IMAGE: 9,
  COMPARE_REFERENCE_COMPOSITE: 10,
  STAMP_DIAGNOSTICS: 11,
} as const;

export type MainViewMode = typeof MAIN_VIEW_MODES[keyof typeof MAIN_VIEW_MODES];
