import { MAIN_VIEW_MODES } from '../engine/viewModes';
import type { MainViewMode } from '../engine/viewModes';
import { switchRendererPreference } from '../engine/rendererMode';
import type { LayerTriple } from '../state/types';
import type { OverlayProps } from './overlay/types';
import type { AppUIProps } from './AppUI.types';
import type { LayerIndex } from './overlay/types';

export function buildOverlayProps(p: AppUIProps): OverlayProps {
  return {
    layerAngles: p.layerAngles,
    layerExtensions: p.layerExtensions,
    frameRate: p.frameRate,
    layerOpacity: p.layerOpacity,
    layerOpacities: p.layerOpacities,
    layerScale: p.layerScale,
    tracerScale: p.tracerScale,
    tracerAboveIntensity: p.tracerAboveIntensity,
    tracerBelowIntensity: p.tracerBelowIntensity,
    tracerAboveDuration: p.tracerAboveDuration,
    tracerBelowDuration: p.tracerBelowDuration,
    tracerMode: p.tracerMode,
    layerBlendMode: p.layerBlendMode,
    tracerBlendMode: p.tracerBlendMode,
    outputMode: p.outputMode,
    diagnosticsMode: p.diagnosticsMode,
    diagnosticsOpacity: p.diagnosticsOpacity,
    stampBoost: p.stampBoost,
    peakCollisionsOnly: p.peakCollisionsOnly,
    collisionStats: p.collisionStats,
    rendererBackend: p.rendererBackend,
    rendererFallbackReason: p.rendererFallbackReason,
    webglDebugMode: p.webglDebugMode,
    onRendererBackendChange: switchRendererPreference,
    onWebglDebugModeChange: p.setWebglDebugMode,
    xrAvailable: p.xrAvailable,
    xrReason: p.xrReason,
    xrImmersive: p.xrImmersive,
    xrBusy: p.xrBusy,
    xrError: p.xrError,
    xrEnterAllowed: p.xrEnterAllowed,
    kioskEnabled: p.kioskEnabled,
    onEnterXr: p.onEnterXr,
    onExitXr: p.onExitXr,
    mainViewMode: p.mainViewMode,
    isViewingTracer: p.isViewingTracer,
    isPaused: p.isPaused,
    tracerInspectHeatmap: p.tracerInspectHeatmap,
    tracerInspectZoom: p.tracerInspectZoom,
    tracerInspectExposure: p.tracerInspectExposure,
    tracerInspectTonemap: p.tracerInspectTonemap,
    tracerInspectShowLayers: p.tracerInspectShowLayers,
    exportingTracer: p.exportingTracer,
    currentImageLabel: p.currentImage?.label ?? p.currentImage?.url ?? null,
    referenceImageLabel: p.referenceImage?.label ?? p.referenceImage?.url ?? null,
    isImageStripOpen: p.isImageStripOpen,
    referenceBlendMode: p.referenceBlendMode,
    overlayImageSource: p.overlayImageSource,
    referenceOpacity: p.referenceOpacity,
    onTracerViewToggle: (next) => p.setMainViewMode(
      next ? MAIN_VIEW_MODES.FULL_RES_TRACER : MAIN_VIEW_MODES.PROCESSED_COMPOSITE,
    ),
    onMainViewModeChange: (value: number) => p.setMainViewMode(value as MainViewMode),
    onEngineModeChange: (mode) => {
      if (mode === 'wasm' && !p.isWasmReady()) return;
      p.setEngineMode(mode);
    },
    onToggleImageStrip: p.toggleImageStrip,
    onSwapSourceReference: p.swapSourceAndReference,
    onReferenceBlendModeChange: p.setReferenceBlendMode,
    onOverlayImageSourceChange: p.setOverlayImageSource,
    onReferenceOpacityChange: p.setReferenceOpacity,
    onFreezeInspect: p.handleFreezeInspect,
    onTracerInspectHeatmapToggle: p.setTracerInspectHeatmap,
    onTracerInspectZoomChange: p.setTracerInspectZoom,
    onTracerInspectExposureChange: p.setTracerInspectExposure,
    onTracerInspectTonemapToggle: p.setTracerInspectTonemap,
    onTracerInspectShowLayersToggle: p.setTracerInspectShowLayers,
    onResetInspectView: p.handleResetInspectView,
    onExportTracer: p.handleExportTracer,
    exportingVideo: p.exportingVideo,
    videoExportProgress: p.videoExportProgress,
    videoExportSettings: p.videoExportSettings,
    codecSupport: p.codecSupport,
    onExportVideo: p.handleExportVideo,
    onCancelVideoExport: p.handleCancelVideoExport,
    onVideoExportDurationChange: p.onVideoExportDurationChange,
    onVideoExportFpsChange: p.onVideoExportFpsChange,
    onVideoExportScaleChange: p.onVideoExportScaleChange,
    onVideoExportIncludeTracersChange: p.onVideoExportIncludeTracersChange,
    onVideoExportPassModeChange: p.onVideoExportPassModeChange,
    onVideoExportFilenameChange: p.onVideoExportFilenameChange,
    onVideoExportUsePresetAnglesChange: p.onVideoExportUsePresetAnglesChange,
    squareCanvas: p.squareCanvas,
    antialiasEnabled: p.antialiasEnabled,
    viewportQuarterZoom: p.viewportQuarterZoom,
    viewportHalfOverlay: p.viewportHalfOverlay,
    onAngleChange: p.handleAngleChange,
    onExtensionChange: p.handleExtensionChange,
    onFrameRateChange: p.setFrameRate,
    onLayerOpacityChange: p.setLayerOpacity,
    onLayerOpacityPerLayerChange: (layer: LayerIndex, opacity: number) => {
      const next = [...p.layerOpacities] as LayerTriple<number>;
      next[layer] = opacity;
      p.setLayerOpacities(next);
    },
    onLayerScaleChange: p.setLayerScale,
    onTracerScaleChange: p.setTracerScale,
    onTracerAboveIntensityChange: p.setTracerAboveIntensity,
    onTracerBelowIntensityChange: p.setTracerBelowIntensity,
    onTracerAboveDurationChange: p.setTracerAboveDuration,
    onTracerBelowDurationChange: p.setTracerBelowDuration,
    onTracerModeChange: p.setTracerMode,
    onLayerBlendModeChange: p.setLayerBlendMode,
    onTracerBlendModeChange: p.setTracerBlendMode,
    onOutputModeChange: p.setOutputMode,
    onDiagnosticsModeChange: p.setDiagnosticsMode,
    onDiagnosticsOpacityChange: p.setDiagnosticsOpacity,
    onStampBoostChange: p.setStampBoost,
    onPeakCollisionsOnlyChange: p.setPeakCollisionsOnly,
    performanceHudEnabled: p.performanceHudEnabled,
    performanceAutoDegrade: p.performanceAutoDegrade,
    performanceBudgetExceeded: p.performanceBudgetExceeded,
    renderCpuTiming: p.renderCpuTiming,
    renderGpuTiming: p.renderGpuTiming,
    frameTimeHistory: p.frameTimeHistory,
    onPerformanceHudToggle: p.setPerformanceHudEnabled,
    onPerformanceAutoDegradeToggle: p.setPerformanceAutoDegrade,
    onApplyPerformanceDegrade: () => {
      p.rendererRef.current?.setAntialiasing(false);
      p.applyPerformanceDegrade();
    },
    colorMode: p.colorMode,
    onColorModeChange: p.setColorMode,
    sobelEnabled: p.sobelEnabled,
    onSobelEnabledToggle: p.setSobelEnabled,
    softCropEnabled: p.softCropEnabled,
    onSoftCropEnabledToggle: p.setSoftCropEnabled,
    onSquareCanvasToggle: p.setSquareCanvas,
    onAntialiasToggle: (enabled) => {
      p.setAntialiasEnabled(enabled);
      p.rendererRef.current?.setAntialiasing(enabled);
    },
    onViewportQuarterZoomToggle: (enabled) => {
      p.setViewportQuarterZoom(enabled);
      if (enabled) p.setViewportHalfOverlay(false);
    },
    onViewportHalfOverlayToggle: (enabled) => {
      p.setViewportHalfOverlay(enabled);
      if (enabled) p.setViewportQuarterZoom(false);
    },
    onReset: p.handleReset,
    builtinPresets: p.builtinPresets,
    savedPresets: p.savedPresets,
    presetStatus: p.presetStatus,
    presetError: p.presetError,
    onSavePreset: p.handleSavePreset,
    onLoadPreset: p.handleLoadPreset,
    onDeletePreset: p.handleDeletePreset,
    onApplyBuiltinPreset: p.handleApplyBuiltinPreset,
    onCopyPresetUrl: p.handleCopyPresetUrl,
    compareLayout: p.compareLayout,
    compareSyncPlay: p.compareSyncPlay,
    compareDualAvailable: p.compareDualAvailable,
    comparePerformanceNote: p.comparePerformanceNote,
    onCompareLayoutChange: p.onCompareLayoutChange,
    onCompareSyncPlayToggle: p.onCompareSyncPlayToggle,
    onCompareWithBuiltin: p.onCompareWithBuiltin,
    onCompareWithSaved: p.onCompareWithSaved,
    onExportPresetFile: p.handleExportPresetFile,
    onImportPresetFile: p.handleImportPresetFile,
    isAutoPlayActive: p.isAutoPlayActive,
    onAutoPlayToggle: p.setIsAutoPlayActive,
    imageChangeInterval: p.imageChangeInterval,
    onImageChangeIntervalChange: p.setImageChangeInterval,
    onLoadSpecificImage: p.handleLoadSpecificImage,
    onLoadFile: p.handleLoadFile,
    onLoadReferenceImage: p.handleLoadReferenceImage,
    onLoadReferenceFile: p.handleLoadReferenceFile,
    upscaleModel: p.upscaleModel,
    onUpscaleModelChange: p.setUpscaleModel,
    upscaleBusy: p.upscaleBusy,
    upscaleProgress: p.upscaleProgress,
    upscaleInfo: p.upscaleInfo,
    onUpscaleSource: p.handleUpscaleSource,
    onUpscaleOutput: p.handleUpscaleOutput,
    engineMode: p.engineMode,
    wasmAvailable: p.wasmAvailable,
    reactiveEnabled: p.reactiveEnabled,
    audioEnabled: p.audioEnabled,
    midiEnabled: p.midiEnabled,
    micActive: p.micActive,
    micError: p.micError,
    midiAvailable: p.midiAvailable,
    midiError: p.midiError,
    midiLearnTarget: p.midiLearnTarget,
    midiBindings: p.midiBindings,
    audioLevels: p.audioLevels,
    audioSensitivity: p.audioSensitivity,
    layerExtension0: p.layerExtension0,
    onReactiveEnabledChange: p.onReactiveEnabledChange,
    onAudioEnabledChange: p.onAudioEnabledChange,
    onMidiEnabledChange: p.onMidiEnabledChange,
    onAudioSensitivityChange: p.onAudioSensitivityChange,
    onStartMicDemo: p.onStartMicDemo,
    onMidiLearnTargetChange: p.onMidiLearnTargetChange,
    onRemoveMidiBinding: p.onRemoveMidiBinding,
  };
}
