import { isWasmReady } from '../../engine/WasmEngine';
import type { ChromashiftActions } from '../../state/actions';
import type { ChromashiftState } from '../../state/types';
import type { AppUIControlProps, AppUiHandlerBundle } from '../../components/AppUI.types';
import type { WebXrControls } from '../useWebXr';
import type { MainViewportDerived } from './buildMainViewportProps';

export function buildControlProps(
  state: ChromashiftState,
  actions: ChromashiftActions,
  handlers: AppUiHandlerBundle,
  webxr: WebXrControls,
  derived: MainViewportDerived & { isViewingTracer: boolean; currentImage: import('../../engine/TextureManager').ImageEntry | null },
): AppUIControlProps {
  const { layers, tracers, output, engine, ui, reactive } = state;

  return {
    rendererBackend: engine.backend,
    rendererFallbackReason: engine.fallbackReason,
    webglDebugMode: output.webglDebugMode,
    setWebglDebugMode: actions.setWebglDebugMode,
    isAutoPlayActive: ui.isAutoPlayActive,
    setIsAutoPlayActive: actions.setIsAutoPlayActive,
    handleLoadFile: handlers.handleLoadFile,
    handleLoadSpecificImage: handlers.handleLoadSpecificImage,
    handleLoadReferenceFile: handlers.handleLoadReferenceFile,
    handleLoadReferenceImage: handlers.handleLoadReferenceImage,
    handleDropFiles: handlers.handleDropFiles,
    swapSourceAndReference: handlers.swapSourceAndReference,
    setReferenceBlendMode: actions.setReferenceBlendMode,
    setOverlayImageSource: actions.setOverlayImageSource,
    setReferenceOpacity: actions.setReferenceOpacity,
    handleFreezeInspect: handlers.handleFreezeInspect,
    tracerInspectZoom: output.tracerInspect.zoom,
    setTracerInspectZoom: actions.setTracerInspectZoom,
    tracerInspectHeatmap: output.tracerInspect.heatmap,
    setTracerInspectHeatmap: actions.setTracerInspectHeatmap,
    tracerInspectExposure: output.tracerInspect.exposure,
    setTracerInspectExposure: actions.setTracerInspectExposure,
    tracerInspectTonemap: output.tracerInspect.tonemap,
    setTracerInspectTonemap: actions.setTracerInspectTonemap,
    tracerInspectShowLayers: output.tracerInspect.showLayers,
    setTracerInspectShowLayers: actions.setTracerInspectShowLayers,
    handleResetInspectView: actions.resetInspectView,
    exportingTracer: ui.exportingTracer,
    handleExportTracer: handlers.handleExportTracer,
    exportingVideo: handlers.exportingVideo,
    videoExportProgress: handlers.videoExportProgress,
    videoExportSettings: handlers.videoExportSettings,
    codecSupport: handlers.codecSupport,
    handleExportVideo: handlers.handleExportVideo,
    handleCancelVideoExport: handlers.handleCancelVideoExport,
    onVideoExportDurationChange: handlers.onVideoExportDurationChange,
    onVideoExportFpsChange: handlers.onVideoExportFpsChange,
    onVideoExportScaleChange: handlers.onVideoExportScaleChange,
    onVideoExportIncludeTracersChange: handlers.onVideoExportIncludeTracersChange,
    onVideoExportPassModeChange: handlers.onVideoExportPassModeChange,
    onVideoExportFilenameChange: handlers.onVideoExportFilenameChange,
    onVideoExportUsePresetAnglesChange: handlers.onVideoExportUsePresetAnglesChange,
    onVideoExportContainerChange: handlers.onVideoExportContainerChange,
    onVideoExportQualityChange: handlers.onVideoExportQualityChange,
    builtinPresets: handlers.builtinPresets,
    savedPresets: handlers.savedPresets,
    presetStatus: handlers.presetStatus,
    presetError: handlers.presetError ?? ui.presetLoadError,
    handleSavePreset: handlers.handleSavePreset,
    handleLoadPreset: handlers.handleLoadPreset,
    handleDeletePreset: handlers.handleDeletePreset,
    handleApplyBuiltinPreset: handlers.handleApplyBuiltinPreset,
    handleCopyPresetUrl: handlers.handleCopyPresetUrl,
    handleExportPresetFile: handlers.handleExportPresetFile,
    handleImportPresetFile: handlers.handleImportPresetFile,
    colorProfiles: handlers.colorProfiles,
    compareLayout: ui.compareView.layout,
    compareSyncPlay: ui.compareView.syncPlay,
    compareDualAvailable: engine.backend === 'webgpu' && !ui.kioskEnabled,
    comparePerformanceNote: derived.comparePerformanceNote,
    onCompareLayoutChange: actions.setCompareLayout,
    onCompareSyncPlayToggle: actions.setCompareSyncPlay,
    onCompareSwipePositionChange: actions.setCompareSwipePosition,
    onCompareWithBuiltin: handlers.handleCompareWithBuiltin,
    onCompareWithSaved: handlers.handleCompareWithSaved,
    layerAngles: layers.angles,
    handleAngleChange: handlers.handleAngleChange,
    layerExtensions: layers.extensions,
    handleExtensionChange: handlers.handleExtensionChange,
    frameRate: engine.fps,
    setFrameRate: actions.setFrameRate,
    layerOpacity: layers.opacity,
    setLayerOpacity: actions.setLayerOpacity,
    layerOpacities: layers.opacities,
    setLayerOpacities: actions.setLayerOpacities,
    layerScale: layers.scale,
    setLayerScale: actions.setLayerScale,
    tracerScale: tracers.scale,
    setTracerScale: actions.setTracerScale,
    tracerAboveIntensity: tracers.aboveIntensity,
    setTracerAboveIntensity: actions.setTracerAboveIntensity,
    tracerBelowIntensity: tracers.belowIntensity,
    setTracerBelowIntensity: actions.setTracerBelowIntensity,
    tracerAboveDuration: tracers.aboveDuration,
    setTracerAboveDuration: actions.setTracerAboveDuration,
    tracerBelowDuration: tracers.belowDuration,
    setTracerBelowDuration: actions.setTracerBelowDuration,
    tracerMode: tracers.mode,
    setTracerMode: actions.setTracerMode,
    layerBlendMode: tracers.layerBlendMode,
    setLayerBlendMode: actions.setLayerBlendMode,
    tracerBlendMode: tracers.tracerBlendMode,
    setTracerBlendMode: actions.setTracerBlendMode,
    outputMode: output.outputMode,
    setOutputMode: actions.setOutputMode,
    diagnosticsMode: output.diagnosticsMode,
    setDiagnosticsMode: actions.setDiagnosticsMode,
    diagnosticsOpacity: output.diagnosticsOpacity,
    setDiagnosticsOpacity: actions.setDiagnosticsOpacity,
    stampBoost: output.stampBoost,
    setStampBoost: actions.setStampBoost,
    peakCollisionsOnly: output.peakCollisionsOnly,
    setPeakCollisionsOnly: actions.setPeakCollisionsOnly,
    performanceAutoDegrade: output.performanceAutoDegrade,
    setPerformanceHudEnabled: actions.setPerformanceHudEnabled,
    setPerformanceAutoDegrade: actions.setPerformanceAutoDegrade,
    performanceBudgetExceeded: ui.performanceBudgetExceeded,
    renderGpuTiming: ui.renderGpuTiming,
    frameTimeHistory: ui.frameTimeHistory,
    applyPerformanceDegrade: actions.applyPerformanceDegrade,
    colorMode: layers.colorMode,
    setColorMode: actions.setColorMode,
    sobelEnabled: layers.sobelEnabled,
    setSobelEnabled: actions.setSobelEnabled,
    softCropEnabled: layers.softCropEnabled,
    setSoftCropEnabled: actions.setSoftCropEnabled,
    viewportQuarterZoom: output.viewportQuarterZoom,
    setViewportQuarterZoom: actions.setViewportQuarterZoom,
    viewportHalfOverlay: output.viewportHalfOverlay,
    setViewportHalfOverlay: actions.setViewportHalfOverlay,
    squareCanvas: output.squareCanvas,
    setSquareCanvas: actions.setSquareCanvas,
    antialiasEnabled: output.antialiasEnabled,
    setAntialiasEnabled: actions.setAntialiasEnabled,
    handleReset: handlers.handleReset,
    imageChangeInterval: ui.imageChangeInterval,
    setImageChangeInterval: actions.setImageChangeInterval,
    upscaleModel: ui.upscaleModel,
    setUpscaleModel: actions.setUpscaleModel,
    handleUpscaleSource: handlers.handleUpscaleSource,
    handleUpscaleOutput: handlers.handleUpscaleOutput,
    upscaleBusy: ui.upscaleBusy,
    upscaleProgress: ui.upscaleProgress,
    upscaleInfo: ui.upscaleInfo,
    engineMode: engine.engineMode,
    setEngineMode: actions.setEngineMode,
    wasmAvailable: engine.wasmAvailable,
    xrAvailable: webxr.xrAvailable,
    xrReason: webxr.xrReason,
    xrImmersive: webxr.xrImmersive,
    xrBusy: webxr.xrBusy,
    xrError: webxr.xrError,
    xrEnterAllowed: webxr.xrEnterAllowed,
    onEnterXr: () => { void webxr.enterXr(); },
    onExitXr: webxr.exitXr,
    isViewingTracer: derived.isViewingTracer,
    currentImage: derived.currentImage,
    isWasmReady,
    kioskEnabled: ui.kioskEnabled,
    reactiveEnabled: reactive.enabled,
    audioEnabled: reactive.audioEnabled,
    midiEnabled: reactive.midiEnabled,
    micActive: reactive.micActive,
    micError: reactive.micError,
    midiAvailable: reactive.midiAvailable,
    midiError: reactive.midiError,
    midiLearnTarget: reactive.midiLearnTarget,
    midiBindings: reactive.midiBindings,
    audioLevels: reactive.audioLevels,
    audioSensitivity: reactive.audioSensitivity,
    layerExtension0: layers.extensions[0],
    onReactiveEnabledChange: actions.setReactiveEnabled,
    onAudioEnabledChange: actions.setReactiveAudioEnabled,
    onMidiEnabledChange: actions.setReactiveMidiEnabled,
    onAudioSensitivityChange: actions.setReactiveAudioSensitivity,
    onStartMicDemo: () => {
      actions.setReactiveEnabled(true);
      actions.setReactiveAudioEnabled(true);
    },
    onMidiLearnTargetChange: actions.setMidiLearnTarget,
    onRemoveMidiBinding: actions.removeMidiBinding,
  };
}
